### ISSUE TITLE
Results in Maze navigation

### ISSUE THREAD

**Issue by CeHao1** [clvrai/skimo#2]
Hello, I am very interested in this work. I have a question about the SPiRL baseline in Maze navigation task (Figure 4, left).

In this paper, Figure 4 left,  at 2M steps, the success rate is only about 0.6. However, in the original SPIRL paper, at 1.4M steps, the success rate is almost 100%. https://clvrai.github.io/spirl/.

Also in the Kitchen env, the results are different from the SPiRL paper.

I check this repo and you are basically using the same code as SPiRL. So did you know what made this big difference? Or because you changed the original environment? Thanks.

**Comment by youngwoon** [comment]
Hi, 

First of all, we use the improved version of SPiRL introduced in SkiLD (https://clvrai.com/skild), a follow-up of SPiRL, and this leads to the improved Kitchen results.

For the maze environment, we use the one from SkiLD. The main difference compared to SPiRL's maze environment is that we use the same training and testing maze, so that the observation is simply the (x, y) coordinate of the point mass agent.
However, in SPiRL, the pre-training data is collected from random mazes and thus, the observation space is a local maze observation.

**Comment by CeHao1** [comment]
Great thanks for the reply! I understand the difference of observation. I would like to follow your work and your advice is very valuable!
